---
title: "Outreach"
---

<br>

### Press articles  

Portafolio (Colombia) - op-ed: <a href="https://www.portafolio.co/economia/colombia-es-la-hora-de-la-redistribucion-thomas-piketty-562033">Colombia, es la hora de la redistribución</a> with Oscar Barrera and Thomas Piketty, 22 Feb 2022 

Tercera dosis (Chile) - Interview: <a href="https://terceradosis.cl/2021/12/10/quien-crece-cuando-chile-crece/">¿Quién crece cuando Chile crece?</a>, Dec 2021

Stone center (United States) - <a href="https://stonecenter.gc.cuny.edu/measuring-inequality-in-latin-america-a-conversation-with-stone-center-postdoctoral-scholar-ignacio-flores/">Interview: Measuring Inequality in Latin America</a>, Nov 2021

La Tercera (Chile) - op-ed: <a href="images/oped-flores-piketty.jpeg"> La letra chica del impuesto a la fortuna</a>, with Thomas Piketty, 10 May 2021

La Tercera (Chile) - interview: <a href="https://www.latercera.com/pulso/noticia/chileno-que-trabaja-con-piketty-en-datos-de-desigualdad-chile-se-ubica-en-el-podio-a-nivel-mundial-de-los-paises-mas-desiguales/VASBLDNU35FJPLKNH2HNE3MC74/">Chileno que trabaja con Piketty en datos de desigualdad: “Chile se ubica en el podio a nivel mundial de los países más desiguales”</a>, 24 November 2020

Folha de Sao Paulo (Brazil) - op-ed: <a href="https://www1.folha.uol.com.br/ilustrissima/2020/05/apesar-da-crise-da-covid-19-america-latina-pode-conter-aumento-da-desigualdade.shtml?utm_source=twitter&utm_medium=social&utm_campaign=twfolha/">Apesar da crise da Covid-19, América Latina pode conter aumento da desigualdade</a>, with Mauricio De Rosa and Marc Morgan, 8 May 2020

El País (Spain) - op-ed: <a href="https://elpais.com/economia/2020-05-31/la-crisis-es-inevitable-en-america-latina-la-desigualdad-no.html">La crisis es inevitable en América Latina, la desigualdad no</a>, with Mauricio De Rosa and Marc Morgan, 31 May 2020

Le Monde (France) - op-ed: <a href="http://ignacioflores.com/tribune_lemonde_chilean_crisis.pdf">Au Chili, deux pays coexistent au sein d’un même</a>, 5 Oct 2019

<br>

### Other media

Congreso Futuro (Chile) - speaker: <a href="https://www.youtube.com/watch?v=Zl-QosneKmo"> Las cadenas de la inequidad </a>  

<iframe width="500" height="400" src="https://www.youtube.com/embed/Zl-QosneKmo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

BLU radio (Colombia) - interview: <a href="https://www.bluradio.com/nacion/datos-de-la-dian-no-dan-suficiente-transparencia-para-evaluar-desigualdad-ignacio-flores">Datos de la DIAN no dan suficiente transparencia para evaluar desigualdad: Ignacio Flores</a>, 19 November 2020

France 24 TV (France) - debate: “Rage against the system: From Chile to Lebanon, why the sudden wave of protests?” France 24 – The Debate, Oct. 22, 2019

