---
title: "Projects"
---

<br>
<br>

### Websites and databases

[WID.world](https://wid.world) - Directors: [Facundo Alvaredo](https://sites.google.com/site/alvaredo/), [Thomas Piketty](http://piketty.pse.ens.fr/en/), [Emmanuel Saez](https://eml.berkeley.edu/~saez/) and [Gabriel Zucman](https://gabriel-zucman.eu). <br> 
(*) I am responsible of the Data on Latin America and the Caribbean, including its progressive improvement and yearly updates. <br> 
<button data-toggle="collapse" data-target="#widworld">	&plus; Description</button>
<div id="widworld" class="collapse">
A project hosted by the [Paris School of Economics](https://www.parisschoolofeconomics.eu), The World Inequality Database is one of the world's most comprehensive data sources on the distribution of income and wealth worldwide. 
</div><br>  

[The GC Wealth Project](https://wealthproject.gc.cuny.edu) - Director: [Salvatore Morelli](https://sites.google.com/site/salvatoremorelli/) <br> (*) I am responsible for designing and overseeing the backend data architecture <br> 
<button data-toggle="collapse" data-target="#gcwealth">	&plus; Description</button>
<div id="gcwealth" class="collapse">
A project of the [Stone Center at the City University of New York](https://stonecenter.gc.cuny.edu), aimed at expanding and consolidating access to the most up-to-date research and information on wealth, wealth inequalities, and wealth transfers and related tax policies, across countries and over time.
</div><br>  

[distribuciones.info](https://distribuciones.info) - with Mauricio De Rosa and Marc Morgan  
<button data-toggle="collapse" data-target="#distri">	&plus; Description</button>
<div id="distri" class="collapse">
An analytical project focusing on economic growth distribution in Latin America, showcasing detailed results from our research to highlight income disparities and the representation of wealthier demographics. It's designed for a broad audience, enabling easy exploration, documentation, and download of the data.
</div><br>  


### Open source software 

[ineqstats:](https://github.com/ignacio-flores/ineqstats) A Stata program developed for summarizing survey micro-data with weighted observations across various distributional dimensions. <br>
<button data-toggle="collapse" data-target="#ineqs">	&plus; Description</button>
<div id="ineqs" class="collapse">
It handles large data volumes, including information from different areas (countries or regions), over various time periods. This command is especially useful for comprehensive analysis of income and wealth distribution.
</div><br>  

[bfmtoy:](https://github.com/ignacio-flores/bfmtoy) A Stata package designed to simulate income distributions and draw biased samples. <br>
<button data-toggle="collapse" data-target="#bfmt">	&plus; Description</button>
<div id="bfmt" class="collapse">
This tool is tailored for researchers and analysts working in economic and social sciences, providing a way to analyze the impact of bias in survey data. It integrates seamlessly with Stata commands like bfmcorr and postbfm for advanced analyses.
</div><br>  

